resources:
- https://github.com/minio/operator/examples/kustomization/base?ref=v7.1.1

patches:
- target:
    kind: Tenant
    name: myminio
  patch: |-
    - op: replace
      path: /spec/pools/0/servers
      value: 1
    - op: replace
      path: /spec/pools/0/volumesPerServer
      value: 4
    - op: replace
      path: /spec/pools/0/volumeClaimTemplate/spec/resources/requests/storage
      value: 5Gi
    - op: add
      path: /spec/pools/0/resources
      value:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"