resources:
- https://github.com/minio/operator?ref=v7.1.1
- https://github.com/minio/operator/examples/kustomization/base?ref=v7.1.1

patches:
- target:
    kind: Deployment
    name: minio-operator
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target: 
    kind: Tenant
    name: myminio
  patch: |-
    - op: replace
      path: /spec/pools/0/servers
      value: 1 
    - op: replace
      path: /spec/pools/0/volumesPerServer
      value: 4
    - op: replace
      path: /spec/pools/0/volumeClaimTemplate/spec/resources/requests/storage
      value: 5Gi