apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

resources:
  - apicurio-registry-namespace.yaml
  - apicurio-registry-deployment.yaml
  - apicurio-registry-service.yaml