apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests/gravitino

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: gravitino
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: gravitino
