apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../manifests/gravitino

patches:
  - path: patch-gravitino-deployment.yaml
    target:
      kind: Deployment
      name: gravitino
  - path: patch-gravitino-configmap.yaml
    target:
      kind: ConfigMap
      name: gravitino
  - path: patch-iceberg-rest-configmap.yaml
    target:
      kind: ConfigMap
      name: gravitino-iceberg-rest-server
  - path: patch-iceberg-rest-deployment.yaml
    target:
      kind: Deployment
      name: gravitino-iceberg-rest-server
