apiVersion: apps/v1
kind: Deployment
metadata:
  name: gravitino
  namespace: metadata
spec:
  selector:
    matchLabels:
      app: gravitino
  template:
    metadata:
      labels:
        app: gravitino
    spec:
      containers:
      - name: gravitino
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
