apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-app-data
  labels:
    app: recommendation-app-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-app-data
  template:
    metadata:
      labels:
        app: recommendation-app-data
    spec:
      containers:
        - name: data-generator
          image: quay.io/streamshub/flink-examples-data-generator:main
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
            - name: DATA
              value: "clickStream,sales,internationalSales"
            - name: USE_APICURIO_REGISTRY
              value: "true"
            - name: REGISTRY_URL
              value: "http://apicurio-registry-service.registry.svc:8080/apis/registry/v2"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"